apiVersion: v1
kind: Secret
metadata:
  name: lanchonete-secret
  namespace: lanchonete-ns
type: Opaque
data:
  postgres_user: dXNlcl9maWFw # Base64 para user_fiap
  postgres_password: cGFzc3dvcmRfZmlhcA== # Base64 para password_fiap
  datasource_username: dXNlcl9maWFw # user_fiap encoded in base64
  datasource_password: cGFzc3dvcmRfZmlhcA== # password_fiap encoded in base64
  access_token: VEVTVC0xODE5OTQzMDI4NzU1NDM4LTEwMDgyMS1jZTUyNGJhMzc4ZWQ0ZGUyZjFlNWM2ZDg2MGU0MzYwNy04MjgzMDQyMA==  # Valor codificado em base64